### ISSUE TITLE
setUserId is not a function

### ISSUE THREAD

**Issue by beldar** [google/chatbase-node#1]
Trying to use this library and keep getting this error, my code looks like this:

```
chatbase.newMessage()
      .setAsTypeUser()
      .setPlatform(event.address.channelId)
      .setVersion(version)
      .setTimestamp(new Date(event.timestamp).getTime())
      .setMessage(event.text)
      .setUserId(event.address.user.id || event.user.id)
      .send()
      .then(msg => console.log(msg.getCreateResponse()))
      .catch(err => console.error(err));
```

Error I get is: 

```
TypeError: chatbase.newMessage(...).setAsTypeUser(...).setPlatform(...).setVersion(...).setTimestamp(...).setMessage(...).setUserId is not a function
```

Running this on:
- Node v7.5.0
- MacOS Sierra v10.12.6 

What am I doing wrong?

Thanks

**Comment by cristiancavalli** [comment]
Hey @beldar thanks for report looking into this now!

**Comment by cristiancavalli** [comment]
@beldar Issue is fixed on master, will release an update to the NPM package and ping this thread.

**Comment by cristiancavalli** [comment]
The fix is now uploaded to the package on NPM:
https://www.npmjs.com/package/@google/chatbase
Version: 0.0.2

Please re-open this issue if this did not fix the issue you were having. Thanks again for reporting this!

**Comment by beldar** [comment]
It did fix this issue, other ones have sprung up, but I'll open other tickets for them.

Thanks for the quick fix! 👌
