### ISSUE TITLE
If setTimestamp is used, throws an error about missing fields

### ISSUE THREAD

**Issue by beldar** [google/chatbase-node#2]
Error I'm getting:
```
Error: One or more required fields were not set on the message, please check the documentation on how to set the following message fields:
api_key, type, user_id, time_stamp, platform, message
```

Code using it:
```
.setTimestamp(new Date(event.timestamp).getTime())
```
which generates a timestamp such as `1503956668941`

If `setTimestamp` is not used, it works fine.

Running this on:

- Node v7.5.0
- MacOS Sierra v10.12.6

Thanks

**Comment by cristiancavalli** [comment]
@beldar Have you tried adding `toString()` to the end of the epoch? We currently only accept stringified epoch's at the API level.

`.setTimestamp(new Date(event.timestamp).getTime().toString())`

**Comment by beldar** [comment]
@cristiancavalli yep, that was it. The error message was very misleading tho...

**Comment by cristiancavalli** [comment]
Hey @beldar thanks for pointing this out -- I'll add some validation logic around this in the client and ping this thread with the commit. Sorry about that..
