### ISSUE TITLE
Sending a message twice with the same messageId converage into one?

### ISSUE THREAD

**Issue by amitbend** [google/chatbase-node#5]
On my bot, I'm sending a new message received through a middleware once it's being routed.
Later sometimes, i want to tag it as a feedback message, or not_handled.
If i'm sending the message once again, with the same `messageId`, will Chatbase know to converge them into one message?

**Comment by cristiancavalli** [comment]
@amitbend Sorry for the latency here -- absolutely but make sure to use the [/api/message/update](https://chatbase.com/documentation/ref) endpoint to update your message at a later point with the `message_id` value returned by the API. The node library also offers a local interface to achieve this interaction which may be viewed on the README.

Please reopen this issue if you encounter trouble with the described policies.

Cheers,
Cris
